backend:
  name: git-gateway
  branch: main

media_folder: "../src/assets"
public_folder: "../public"


collections:
  - name: "cms" # Used in routes, e.g., /admin/collections/blog
    label: "none" # Used in the UI
    folder: "../src/data" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "string"}
      - {label: "descDigital", name: "descDigital", widget: "string"}
      